M48
; DRILL file {KiCad 7.0.5-7.0.5~ubuntu20.04.1} date Thu 15 Jun 2023 03:54:35 PM CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-15T15:54:35+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-7.0.5~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1378
%
G90
G05
T1
X5.45Y-5.0
X5.5Y-2.5134
X8.6Y-2.5
X8.6Y-5.0
T0
M30
